# Generated by Django 4.2 on 2023-04-11 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="partner",
            name="cnpj",
            field=models.CharField(
                error_messages={"unique": "A user with that cpnj already exists."},
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
