# Generated by Django 4.2 on 2023-04-11 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="cep",
            field=models.CharField(
                error_messages={"unique": "A plant with that cep already exists."},
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
